title: "Irancell Security"
author: "Irancell Security"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
mathjax: true
show_excerpts: false
show_frame: true

navigation:
  - {title: Mail, icon: envelope, url: "cs@mtnirancell.ir"}
  - {title: Github, icon: github, url: "https://irancell.ir/"}
  - {title: Feed, icon: rss, url: "/p/1590/contact-us"}

remote_theme: niklasbuschmann/contrast

plugins:
 - jekyll-feed
